package skc.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnneeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnneeAllPropertiesEquals(Annee expected, Annee actual) {
        assertAnneeAutoGeneratedPropertiesEquals(expected, actual);
        assertAnneeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnneeAllUpdatablePropertiesEquals(Annee expected, Annee actual) {
        assertAnneeUpdatableFieldsEquals(expected, actual);
        assertAnneeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnneeAutoGeneratedPropertiesEquals(Annee expected, Annee actual) {
        assertThat(actual)
            .as("Verify Annee auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnneeUpdatableFieldsEquals(Annee expected, Annee actual) {
        assertThat(actual)
            .as("Verify Annee relevant properties")
            .satisfies(a -> assertThat(a.getAn()).as("check an").isEqualTo(expected.getAn()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnneeUpdatableRelationshipsEquals(Annee expected, Annee actual) {
        // empty method
    }
}
