package skc.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MoiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoiAllPropertiesEquals(Moi expected, Moi actual) {
        assertMoiAutoGeneratedPropertiesEquals(expected, actual);
        assertMoiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoiAllUpdatablePropertiesEquals(Moi expected, Moi actual) {
        assertMoiUpdatableFieldsEquals(expected, actual);
        assertMoiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoiAutoGeneratedPropertiesEquals(Moi expected, Moi actual) {
        assertThat(actual)
            .as("Verify Moi auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoiUpdatableFieldsEquals(Moi expected, Moi actual) {
        assertThat(actual)
            .as("Verify Moi relevant properties")
            .satisfies(a -> assertThat(a.getIdmois()).as("check idmois").isEqualTo(expected.getIdmois()))
            .satisfies(a -> assertThat(a.getMois()).as("check mois").isEqualTo(expected.getMois()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoiUpdatableRelationshipsEquals(Moi expected, Moi actual) {
        // empty method
    }
}
